9 sprint
ilizian/java-filmorate pull request #3
Opened 2023-03-29 18:54 UTC by ilizian

Добрый день!

2023-03-30 19:09 UTC, alexache requested changes

2023-03-30 19:09 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/model/Film.java
> +    int id;
Не хватает модификаторов доступа полей

2023-03-30 19:09 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/model/User.java
> +    int id;
Не хватает модификаторов доступа полей

2023-03-30 19:09 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/controller/FilmController.java
> +        if (film.getName() == null || film.getName().isEmpty()) {
Почему бы многие из этих проверок не сделать аннотациями на классе?

2023-03-30 19:09 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/controller/UserController.java
> +        if (user.getId() > 0) {
Как по мне - лишние условие. достаточно искать наличие в мапе

2023-03-30 21:13 UTC, ilizian commented
Спасибо за комментарии. Подправил

2023-03-31 14:16 UTC, alexache requested changes

2023-03-31 14:16 UTC, alexache commented on src/test/java/ru.yandex.practicum.filmorate/controller/UserControllerTest.java
> -    void addUserWrongEmailEmpty() {
Тесты на валидации хорошо бы вернуть обратно. Есть другой способ их проверки, когда они сделаны через аннотации:
В инит
    validatorFactory = Validation.buildDefaultValidatorFactory();
    validator = validatorFactory.getValidator();
    
и в тест методе validator.validate, остальные детали можно подсмотреть в поиске

2023-03-31 16:40 UTC, ilizian commented
Спасибо! Подправил

2023-04-01 18:07 UTC, alexache approved these changes

2023-04-03 14:14 UTC, merged