10 sprint 1 version
ilizian/java-filmorate pull request #4
Opened 2023-04-04 21:37 UTC by ilizian

2023-04-05 18:11 UTC, alexache requested changes

2023-04-05 18:11 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/controller/FilmController.java
> +    public Collection<Film> getTopFilms(@RequestParam(defaultValue = "10") @Positive int count) {
Для корректной работы валидаций требуется еще аннотация @Validated на классе

2023-04-05 18:11 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/controller/UserController.java
> +    public List<User> getCommonFriends(@PathVariable long id1, @PathVariable long id2) throws NotFoundException {
Лучше переменные, аргументы называть более осмысленными названиями - user, otherUser

2023-04-05 18:11 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/model/Film.java
> +    private final List<Long> likes = new ArrayList<>();
Могут ли лайки от пользователей повторяться? Если нет, то какая структура данных лучше подойдет?

2023-04-05 18:11 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/model/User.java
> +    private final List<Long> friends = new ArrayList<>();
Здесь такой же вопрос - уникальные ли айди юзеров друзей?

2023-04-05 18:11 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/service/FilmService.java
> +    private final UserService userService;
Сервисам лучше взаимодействовать со стораджами, а не с другими сервисами сущностей

2023-04-05 20:04 UTC, ilizian commented on src/main/java/ru.yandex.practicum.filmorate/service/FilmService.java
> +    private final UserService userService;
Спасибо за замечания! Исправил

2023-04-06 19:10 UTC, alexache approved these changes

2023-04-08 16:06 UTC, merged