Sprint 11
ilizian/java-filmorate pull request #6
Opened 2023-04-13 16:23 UTC by ilizian

2023-04-14 18:15 UTC, alexache requested changes

2023-04-14 18:15 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/model/Film.java
> +    private final LinkedHashSet<Genre> genres = new LinkedHashSet<>();
Лучше записать как private final Set<Genre> genres - лучше интерфейсы вместо конкретныз реализаций

2023-04-14 18:15 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/service/GenreService.java
> +    private final GenreDbStorage genreDbStorage;
Должен быть интерфейс вместо конкретной реализации

2023-04-14 18:15 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/storage/db/FilmDbStorage.java
> +                    mpaStorage.getMpaById(resultSet.getInt("mpa_id")),
Это нужно сделать через джоин, чтобы избегать запроса к базе в цикле

2023-04-14 18:15 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/storage/db/LikesDbStorage.java
> +                    mpaStorage.getMpaById(resultSet.getInt("mpa_id")),
Тут тоже джоина не хватает

2023-04-14 18:15 UTC, alexache commented on src/main/resources/schema.sql
> +    rate Integer
Что это за поле?

2023-04-14 23:11 UTC, ilizian commented on src/main/java/ru.yandex.practicum.filmorate/model/Film.java
> +    private final LinkedHashSet<Genre> genres = new LinkedHashSet<>();
Да, но, как я понимаю, важен порядок вывода. Тесты в postman иначе не проходит :(

2023-04-14 23:12 UTC, ilizian commented on src/main/java/ru.yandex.practicum.filmorate/service/GenreService.java
> +    private final GenreDbStorage genreDbStorage;
Извиняюсь, но не понимаю что тут именно не так...

2023-04-14 23:17 UTC, ilizian commented on src/main/resources/schema.sql
> +    rate Integer
Немного изменил код в части обновления поля rate. Данное поле хранит кол-во лайков, но при этом в тестовых запросах есть изменение значения rate без добавления лайков (в таблицу likes)

2023-04-14 23:19 UTC, ilizian commented
Добрый день! Спасибо за комментарии. Выше дал пояснения. Readme не попал сначала в пулреквест, сейчас добавил.

2023-04-15 22:25 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/model/Film.java
> +    private final LinkedHashSet<Genre> genres = new LinkedHashSet<>();
Я ведь имею в виду private final Set<Genre> genres = new LinkedHashSet<>(); - реализация пусть будет такая, но тип у поля лучше интерфейс

2023-04-15 22:27 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/service/GenreService.java
> +    private final GenreDbStorage genreDbStorage;
private final GenreStorage genreStorage - так правильно с интерфейсом, а не конкретной имплементацией интерфейса

2023-04-15 22:34 UTC, alexache approved these changes

2023-04-15 22:34 UTC, alexache commented on src/main/java/ru.yandex.practicum.filmorate/storage/db/LikesDbStorage.java
> +                "UPDATE films SET rate = rate + 1 WHERE films.film_id = ?";
Может как-то надежнее получать количество лайков и пересчитывать рейт нежели просто инкрементировать?

2023-04-24 17:14 UTC, merged